(bug) fix errors due to sidekiq upgrade
- NoMethodError: undefined method 'delay' for UsersMailer:Class
- Removed open_api_calls_count_tracings fixtures due to the removal of the related table