(bug) Unable to import accounts from SSO
When the transformation modal was opened but leaved empty, the field
mapping.transformation.type is defined but not
mapping.transformation.mapping, which result in the following error:

NoMethodError (undefined method `each' for nil:NilClass):

lib/omni_auth/data_mapping/base.rb:16:in `map_transformation'